import { setupWorker } from "msw/browser";
import { handlers } from "./handlers";

/**
 * MSW browser worker. Started from main.tsx when VITE_ENABLE_MOCKS=true.
 *
 * The worker file itself (mockServiceWorker.js) lives in /public and is
 * generated by `npm run msw:init`. Until then, MSW will warn but not crash.
 */
export const worker = setupWorker(...handlers);
