/* AUTO-GENERATED by scripts/gen-routes.mjs. Do not edit by hand. */
import type { RouteObject } from "react-router-dom";

import { AdminAcademicYearEditPage as AdminAcademicYearEditPage_RoleAdminAcademicYearsParamIdEdit } from "@/pages/role/admin/academic-years/Param_id/edit";
import { AdminAcademicYearCreatePage as AdminAcademicYearCreatePage_RoleAdminAcademicYearsCreate } from "@/pages/role/admin/academic-years/create";
import { AdminAcademicYearPage as AdminAcademicYearPage_RoleAdminAcademicYears } from "@/pages/role/admin/academic-years";
import { AdminAIPage as AdminAIPage_RoleAdminAi } from "@/pages/role/admin/ai";
import { AdminAnnouncementCreatePage as AdminAnnouncementCreatePage_RoleAdminAnnouncementsCreate } from "@/pages/role/admin/announcements/create";
import { AdminAnnouncementsPage as AdminAnnouncementsPage_RoleAdminAnnouncements } from "@/pages/role/admin/announcements";
import { AdminAttendanceCreatePage as AdminAttendanceCreatePage_RoleAdminAttendanceCreate } from "@/pages/role/admin/attendance/create";
import { AdminAttendancePage as AdminAttendancePage_RoleAdminAttendance } from "@/pages/role/admin/attendance";
import { AdminBehaviorCreatePage as AdminBehaviorCreatePage_RoleAdminBehaviorCreate } from "@/pages/role/admin/behavior/create";
import { BehaviorPage as BehaviorPage_RoleAdminBehavior } from "@/pages/role/admin/behavior";
import { ClassEditPage as ClassEditPage_RoleAdminClassesParamIdEdit } from "@/pages/role/admin/classes/Param_id/edit";
import { ClassFeePage as ClassFeePage_RoleAdminClassesParamIdFee } from "@/pages/role/admin/classes/Param_id/fee";
import { Page as Page_RoleAdminClassesParamIdFees } from "@/pages/role/admin/classes/Param_id/fees";
import { AdminClassCreatePage as AdminClassCreatePage_RoleAdminClassesCreate } from "@/pages/role/admin/classes/create";
import { AdminClassesPage as AdminClassesPage_RoleAdminClasses } from "@/pages/role/admin/classes";
import { ConnectDomainPage as ConnectDomainPage_RoleAdminConnectDomain } from "@/pages/role/admin/connect-domain";
import { AdminDashboardPage as AdminDashboardPage_RoleAdminDashboard } from "@/pages/role/admin/dashboard";
import { AdminEventCreatePage as AdminEventCreatePage_RoleAdminEventsCreate } from "@/pages/role/admin/events/create";
import { EventsPage as EventsPage_RoleAdminEvents } from "@/pages/role/admin/events";
import { AdminExamCreatePage as AdminExamCreatePage_RoleAdminExamsCreate } from "@/pages/role/admin/exams/create";
import { AdminExamsPage as AdminExamsPage_RoleAdminExams } from "@/pages/role/admin/exams";
import { AdminExamMarksPage as AdminExamMarksPage_RoleAdminExamsMarks } from "@/pages/role/admin/exams/marks";
import { StudentFeeDashboard as StudentFeeDashboard_RoleAdminFee } from "@/pages/role/admin/fee";
import { AdminHomeworkReviewPage as AdminHomeworkReviewPage_RoleAdminHomeworkParamIdReview } from "@/pages/role/admin/homework/Param_id/review";
import { AdminHomeworkCreatePage as AdminHomeworkCreatePage_RoleAdminHomeworkCreate } from "@/pages/role/admin/homework/create";
import { AdminHomeworkEditPage as AdminHomeworkEditPage_RoleAdminHomeworkEditParamId } from "@/pages/role/admin/homework/edit/Param_id";
import { AdminHomeworkPage as AdminHomeworkPage_RoleAdminHomework } from "@/pages/role/admin/homework";
import { AdminLeaveCreatePage as AdminLeaveCreatePage_RoleAdminLeaveCreate } from "@/pages/role/admin/leave/create";
import { LeavePage as LeavePage_RoleAdminLeave } from "@/pages/role/admin/leave";
import { AdminLiveClassCreatePage as AdminLiveClassCreatePage_RoleAdminLiveClassCreate } from "@/pages/role/admin/live-class/create";
import { LiveClassPage as LiveClassPage_RoleAdminLiveClass } from "@/pages/role/admin/live-class";
import { AdminLiveClassesPage as AdminLiveClassesPage_RoleAdminLiveClasses } from "@/pages/role/admin/live-classes";
import { LiveExamPage as LiveExamPage_RoleAdminLiveExam } from "@/pages/role/admin/live-exam";
import { AdminResultCreatePage as AdminResultCreatePage_RoleAdminResultsCreate } from "@/pages/role/admin/results/create";
import { AdminResultsPage as AdminResultsPage_RoleAdminResults } from "@/pages/role/admin/results";
import { SalaryPage as SalaryPage_RoleAdminSalary } from "@/pages/role/admin/salary";
import { AdminSettingsPage as AdminSettingsPage_RoleAdminSettings } from "@/pages/role/admin/settings";
import { AdminStudentCreatePage as AdminStudentCreatePage_RoleAdminStudentsCreate } from "@/pages/role/admin/students/create";
import { AdminStudentsPage as AdminStudentsPage_RoleAdminStudents } from "@/pages/role/admin/students";
import { SubjectsPage as SubjectsPage_RoleAdminSubjects } from "@/pages/role/admin/subjects";
import { AdminTeacherCreatePage as AdminTeacherCreatePage_RoleAdminTeachersCreate } from "@/pages/role/admin/teachers/create";
import { AdminTeachersPage as AdminTeachersPage_RoleAdminTeachers } from "@/pages/role/admin/teachers";
import { AdminTimetableCreatePage as AdminTimetableCreatePage_RoleAdminTimetableCreate } from "@/pages/role/admin/timetable/create";
import { AdminTimetableEditPage as AdminTimetableEditPage_RoleAdminTimetableEditParamId } from "@/pages/role/admin/timetable/edit/Param_id";
import { TimetableRoute as TimetableRoute_RoleAdminTimetable } from "@/pages/role/admin/timetable";
import { TeacherAnnouncementCreatePage as TeacherAnnouncementCreatePage_RoleTeacherAnnouncementsCreate } from "@/pages/role/teacher/announcements/create";
import { TeacherAnnouncementsPage as TeacherAnnouncementsPage_RoleTeacherAnnouncements } from "@/pages/role/teacher/announcements";
import { TeacherAttendanceCreatePage as TeacherAttendanceCreatePage_RoleTeacherAttendanceCreate } from "@/pages/role/teacher/attendance/create";
import { TeacherAttendancePage as TeacherAttendancePage_RoleTeacherAttendance } from "@/pages/role/teacher/attendance";
import { TeacherBehaviorCreatePage as TeacherBehaviorCreatePage_RoleTeacherBehaviorCreate } from "@/pages/role/teacher/behavior/create";
import { TeacherBehaviorPage as TeacherBehaviorPage_RoleTeacherBehavior } from "@/pages/role/teacher/behavior";
import { TeacherClassStudentsPage as TeacherClassStudentsPage_RoleTeacherClassesParamIdStudents } from "@/pages/role/teacher/classes/Param_id/students";
import { TeacherClassesPage as TeacherClassesPage_RoleTeacherClasses } from "@/pages/role/teacher/classes";
import { TeacherDashboardPage as TeacherDashboardPage_RoleTeacherDashboard } from "@/pages/role/teacher/dashboard";
import { TeacherEventsPage as TeacherEventsPage_RoleTeacherEvents } from "@/pages/role/teacher/events";
import { TeacherEventCreatePage as TeacherEventCreatePage_RoleTeacherEventsCreate } from "@/pages/role/teacher/events/create";
import { TeacherExamCreatePage as TeacherExamCreatePage_RoleTeacherExamsCreate } from "@/pages/role/teacher/exams/create";
import { TeacherExamsPage as TeacherExamsPage_RoleTeacherExams } from "@/pages/role/teacher/exams";
import { TeacherExamMarksPage as TeacherExamMarksPage_RoleTeacherExamsMarks } from "@/pages/role/teacher/exams/marks";
import { TeacherHomeworkReviewPage as TeacherHomeworkReviewPage_RoleTeacherHomeworkParamIdReview } from "@/pages/role/teacher/homework/Param_id/review";
import { TeacherHomeworkCreatePage as TeacherHomeworkCreatePage_RoleTeacherHomeworkCreate } from "@/pages/role/teacher/homework/create";
import { TeacherHomeworkEditPage as TeacherHomeworkEditPage_RoleTeacherHomeworkEditParamId } from "@/pages/role/teacher/homework/edit/Param_id";
import { TeacherHomeworkPage as TeacherHomeworkPage_RoleTeacherHomework } from "@/pages/role/teacher/homework";
import { TeacherPortalIndexPage as TeacherPortalIndexPage_RoleTeacher } from "@/pages/role/teacher";
import { TeacherLiveClassCreatePage as TeacherLiveClassCreatePage_RoleTeacherLiveClassCreate } from "@/pages/role/teacher/live-class/create";
import { TeacherLiveClassPage as TeacherLiveClassPage_RoleTeacherLiveClass } from "@/pages/role/teacher/live-class";
import { LiveExamMonitorPage as LiveExamMonitorPage_RoleTeacherLiveExamParamIdMonitor } from "@/pages/role/teacher/live-exam/Param_id/monitor";
import { ExamQuestionsPage as ExamQuestionsPage_RoleTeacherLiveExamParamIdQuestions } from "@/pages/role/teacher/live-exam/Param_id/questions";
import { TeacherLiveExamPage as TeacherLiveExamPage_RoleTeacherLiveExam } from "@/pages/role/teacher/live-exam";
import { TeacherResultCreatePage as TeacherResultCreatePage_RoleTeacherResultsCreate } from "@/pages/role/teacher/results/create";
import { TeacherResultsPage as TeacherResultsPage_RoleTeacherResults } from "@/pages/role/teacher/results";
import { TeacherTimetablePage as TeacherTimetablePage_RoleTeacherTimetable } from "@/pages/role/teacher/timetable";
import { ParentAnnouncementsPage as ParentAnnouncementsPage_RoleParentAnnouncements } from "@/pages/role/parent/announcements";
import { ParentAttendancePage as ParentAttendancePage_RoleParentAttendance } from "@/pages/role/parent/attendance";
import { ParentBehaviorPage as ParentBehaviorPage_RoleParentBehavior } from "@/pages/role/parent/behavior";
import { ParentDashboardPage as ParentDashboardPage_RoleParentDashboard } from "@/pages/role/parent/dashboard";
import { ParentEventsPage as ParentEventsPage_RoleParentEvents } from "@/pages/role/parent/events";
import { ParentExamsPage as ParentExamsPage_RoleParentExams } from "@/pages/role/parent/exams";
import { ParentFeesPage as ParentFeesPage_RoleParentFees } from "@/pages/role/parent/fees";
import { ParentHomeworkPage as ParentHomeworkPage_RoleParentHomework } from "@/pages/role/parent/homework";
import { ParentStudentProfilePage as ParentStudentProfilePage_RoleParentProfile } from "@/pages/role/parent/profile";
import { ParentResultsPage as ParentResultsPage_RoleParentResults } from "@/pages/role/parent/results";
import { ParentStudentAttendancePage as ParentStudentAttendancePage_RoleParentStudentAttendance } from "@/pages/role/parent/student-attendance";
import { ParentTimetablePage as ParentTimetablePage_RoleParentTimetable } from "@/pages/role/parent/timetable";
import { StudentAnnouncementsPage as StudentAnnouncementsPage_RoleStudentAnnouncements } from "@/pages/role/student/announcements";
import { StudentAttendancePage as StudentAttendancePage_RoleStudentAttendance } from "@/pages/role/student/attendance";
import { StudentDashboardPage as StudentDashboardPage_RoleStudentDashboard } from "@/pages/role/student/dashboard";
import { StudentEventsPage as StudentEventsPage_RoleStudentEvents } from "@/pages/role/student/events";
import { StudentExamsPage as StudentExamsPage_RoleStudentExams } from "@/pages/role/student/exams";
import { StudentFeesPage as StudentFeesPage_RoleStudentFees } from "@/pages/role/student/fees";
import { StudentHomeworkReviewPage as StudentHomeworkReviewPage_RoleStudentHomeworkParamIdReview } from "@/pages/role/student/homework/Param_id/review";
import { StudentHomeworkPage as StudentHomeworkPage_RoleStudentHomework } from "@/pages/role/student/homework";
import { StudentPortalIndexPage as StudentPortalIndexPage_RoleStudent } from "@/pages/role/student";
import { StudentLiveClassPage as StudentLiveClassPage_RoleStudentLiveClass } from "@/pages/role/student/live-class";
import { StudentLiveExamSessionPage as StudentLiveExamSessionPage_RoleStudentLiveExamParamId } from "@/pages/role/student/live-exam/Param_id";
import { StudentLiveExamPage as StudentLiveExamPage_RoleStudentLiveExam } from "@/pages/role/student/live-exam";
import { StudentProfilePage as StudentProfilePage_RoleStudentProfile } from "@/pages/role/student/profile";
import { StudentResultsPage as StudentResultsPage_RoleStudentResults } from "@/pages/role/student/results";
import { StudentTimetablePage as StudentTimetablePage_RoleStudentTimetable } from "@/pages/role/student/timetable";
import StudentLeavePage from "@/pages/role/student/leave";

export const adminRoutes: RouteObject[] = [
      { path: "/admin/academic-years/:id/edit", element: <AdminAcademicYearEditPage_RoleAdminAcademicYearsParamIdEdit /> },
      { path: "/admin/academic-years/create", element: <AdminAcademicYearCreatePage_RoleAdminAcademicYearsCreate /> },
      { path: "/admin/academic-years", element: <AdminAcademicYearPage_RoleAdminAcademicYears /> },
      { path: "/admin/ai", element: <AdminAIPage_RoleAdminAi /> },
      { path: "/admin/announcements/create", element: <AdminAnnouncementCreatePage_RoleAdminAnnouncementsCreate /> },
      { path: "/admin/announcements", element: <AdminAnnouncementsPage_RoleAdminAnnouncements /> },
      { path: "/admin/attendance/create", element: <AdminAttendanceCreatePage_RoleAdminAttendanceCreate /> },
      { path: "/admin/attendance", element: <AdminAttendancePage_RoleAdminAttendance /> },
      { path: "/admin/behavior/create", element: <AdminBehaviorCreatePage_RoleAdminBehaviorCreate /> },
      { path: "/admin/behavior", element: <BehaviorPage_RoleAdminBehavior /> },
      { path: "/admin/classes/:id/edit", element: <ClassEditPage_RoleAdminClassesParamIdEdit /> },
      { path: "/admin/classes/:id/fee", element: <ClassFeePage_RoleAdminClassesParamIdFee /> },
      { path: "/admin/classes/:id/fees", element: <Page_RoleAdminClassesParamIdFees /> },
      { path: "/admin/classes/create", element: <AdminClassCreatePage_RoleAdminClassesCreate /> },
      { path: "/admin/classes", element: <AdminClassesPage_RoleAdminClasses /> },
      { path: "/admin/connect-domain", element: <ConnectDomainPage_RoleAdminConnectDomain /> },
      { path: "/admin/dashboard", element: <AdminDashboardPage_RoleAdminDashboard /> },
      { path: "/admin/events/create", element: <AdminEventCreatePage_RoleAdminEventsCreate /> },
      { path: "/admin/events", element: <EventsPage_RoleAdminEvents /> },
      { path: "/admin/exams/create", element: <AdminExamCreatePage_RoleAdminExamsCreate /> },
      { path: "/admin/exams", element: <AdminExamsPage_RoleAdminExams /> },
      { path: "/admin/exams/marks", element: <AdminExamMarksPage_RoleAdminExamsMarks /> },
      { path: "/admin/fee", element: <StudentFeeDashboard_RoleAdminFee /> },
      { path: "/admin/homework/:id/review", element: <AdminHomeworkReviewPage_RoleAdminHomeworkParamIdReview /> },
      { path: "/admin/homework/create", element: <AdminHomeworkCreatePage_RoleAdminHomeworkCreate /> },
      { path: "/admin/homework/edit/:id", element: <AdminHomeworkEditPage_RoleAdminHomeworkEditParamId /> },
      { path: "/admin/homework", element: <AdminHomeworkPage_RoleAdminHomework /> },
      { path: "/admin/leave/create", element: <AdminLeaveCreatePage_RoleAdminLeaveCreate /> },
      { path: "/admin/leave", element: <LeavePage_RoleAdminLeave /> },
      { path: "/admin/live-class/create", element: <AdminLiveClassCreatePage_RoleAdminLiveClassCreate /> },
      { path: "/admin/live-class", element: <LiveClassPage_RoleAdminLiveClass /> },
      { path: "/admin/live-classes", element: <AdminLiveClassesPage_RoleAdminLiveClasses /> },
      { path: "/admin/live-exam", element: <LiveExamPage_RoleAdminLiveExam /> },
      { path: "/admin/results/create", element: <AdminResultCreatePage_RoleAdminResultsCreate /> },
      { path: "/admin/results", element: <AdminResultsPage_RoleAdminResults /> },
      { path: "/admin/salary", element: <SalaryPage_RoleAdminSalary /> },
      { path: "/admin/settings", element: <AdminSettingsPage_RoleAdminSettings /> },
      { path: "/admin/students/create", element: <AdminStudentCreatePage_RoleAdminStudentsCreate /> },
      { path: "/admin/students", element: <AdminStudentsPage_RoleAdminStudents /> },
      { path: "/admin/subjects", element: <SubjectsPage_RoleAdminSubjects /> },
      { path: "/admin/teachers/create", element: <AdminTeacherCreatePage_RoleAdminTeachersCreate /> },
      { path: "/admin/teachers", element: <AdminTeachersPage_RoleAdminTeachers /> },
      { path: "/admin/timetable/create", element: <AdminTimetableCreatePage_RoleAdminTimetableCreate /> },
      { path: "/admin/timetable/edit/:id", element: <AdminTimetableEditPage_RoleAdminTimetableEditParamId /> },
      { path: "/admin/timetable", element: <TimetableRoute_RoleAdminTimetable /> }
];

export const teacherRoutes: RouteObject[] = [
      { path: "/teacher/announcements/create", element: <TeacherAnnouncementCreatePage_RoleTeacherAnnouncementsCreate /> },
      { path: "/teacher/announcements", element: <TeacherAnnouncementsPage_RoleTeacherAnnouncements /> },
      { path: "/teacher/attendance/create", element: <TeacherAttendanceCreatePage_RoleTeacherAttendanceCreate /> },
      { path: "/teacher/attendance", element: <TeacherAttendancePage_RoleTeacherAttendance /> },
      { path: "/teacher/behavior/create", element: <TeacherBehaviorCreatePage_RoleTeacherBehaviorCreate /> },
      { path: "/teacher/behavior", element: <TeacherBehaviorPage_RoleTeacherBehavior /> },
      { path: "/teacher/classes/:id/students", element: <TeacherClassStudentsPage_RoleTeacherClassesParamIdStudents /> },
      { path: "/teacher/classes", element: <TeacherClassesPage_RoleTeacherClasses /> },
      { path: "/teacher/dashboard", element: <TeacherDashboardPage_RoleTeacherDashboard /> },
      { path: "/teacher/events", element: <TeacherEventsPage_RoleTeacherEvents /> },
      { path: "/teacher/events/create", element: <TeacherEventCreatePage_RoleTeacherEventsCreate /> },
      { path: "/teacher/exams/create", element: <TeacherExamCreatePage_RoleTeacherExamsCreate /> },
      { path: "/teacher/exams", element: <TeacherExamsPage_RoleTeacherExams /> },
      { path: "/teacher/exams/marks", element: <TeacherExamMarksPage_RoleTeacherExamsMarks /> },
      { path: "/teacher/homework/:id/review", element: <TeacherHomeworkReviewPage_RoleTeacherHomeworkParamIdReview /> },
      { path: "/teacher/homework/create", element: <TeacherHomeworkCreatePage_RoleTeacherHomeworkCreate /> },
      { path: "/teacher/homework/edit/:id", element: <TeacherHomeworkEditPage_RoleTeacherHomeworkEditParamId /> },
      { path: "/teacher/homework", element: <TeacherHomeworkPage_RoleTeacherHomework /> },
      { path: "/teacher", element: <TeacherPortalIndexPage_RoleTeacher /> },
      { path: "/teacher/live-class/create", element: <TeacherLiveClassCreatePage_RoleTeacherLiveClassCreate /> },
      { path: "/teacher/live-class", element: <TeacherLiveClassPage_RoleTeacherLiveClass /> },
      { path: "/teacher/live-exam/:id/monitor", element: <LiveExamMonitorPage_RoleTeacherLiveExamParamIdMonitor /> },
      { path: "/teacher/live-exam/:id/questions", element: <ExamQuestionsPage_RoleTeacherLiveExamParamIdQuestions /> },
      { path: "/teacher/live-exam", element: <TeacherLiveExamPage_RoleTeacherLiveExam /> },
      { path: "/teacher/results/create", element: <TeacherResultCreatePage_RoleTeacherResultsCreate /> },
      { path: "/teacher/results", element: <TeacherResultsPage_RoleTeacherResults /> },
      { path: "/teacher/timetable", element: <TeacherTimetablePage_RoleTeacherTimetable /> }
];

export const parentRoutes: RouteObject[] = [
      { path: "/parent/announcements", element: <ParentAnnouncementsPage_RoleParentAnnouncements /> },
      { path: "/parent/attendance", element: <ParentAttendancePage_RoleParentAttendance /> },
      { path: "/parent/behavior", element: <ParentBehaviorPage_RoleParentBehavior /> },
      { path: "/parent/dashboard", element: <ParentDashboardPage_RoleParentDashboard /> },
      { path: "/parent/events", element: <ParentEventsPage_RoleParentEvents /> },
      { path: "/parent/exams", element: <ParentExamsPage_RoleParentExams /> },
      { path: "/parent/fees", element: <ParentFeesPage_RoleParentFees /> },
      { path: "/parent/homework", element: <ParentHomeworkPage_RoleParentHomework /> },
      { path: "/parent/profile", element: <ParentStudentProfilePage_RoleParentProfile /> },
      { path: "/parent/results", element: <ParentResultsPage_RoleParentResults /> },
      { path: "/parent/student-attendance", element: <ParentStudentAttendancePage_RoleParentStudentAttendance /> },
      { path: "/parent/timetable", element: <ParentTimetablePage_RoleParentTimetable /> }
];

export const studentRoutes: RouteObject[] = [
      { path: "/student/announcements", element: <StudentAnnouncementsPage_RoleStudentAnnouncements /> },
      { path: "/student/attendance", element: <StudentAttendancePage_RoleStudentAttendance /> },
      { path: "/student/dashboard", element: <StudentDashboardPage_RoleStudentDashboard /> },
      { path: "/student/events", element: <StudentEventsPage_RoleStudentEvents /> },
      { path: "/student/exams", element: <StudentExamsPage_RoleStudentExams /> },
      { path: "/student/fees", element: <StudentFeesPage_RoleStudentFees /> },
      { path: "/student/homework/:id/review", element: <StudentHomeworkReviewPage_RoleStudentHomeworkParamIdReview /> },
      { path: "/student/homework", element: <StudentHomeworkPage_RoleStudentHomework /> },
      { path: "/student", element: <StudentPortalIndexPage_RoleStudent /> },
      { path: "/student/live-class", element: <StudentLiveClassPage_RoleStudentLiveClass /> },
      { path: "/student/live-exam/:id", element: <StudentLiveExamSessionPage_RoleStudentLiveExamParamId /> },
      { path: "/student/live-exam", element: <StudentLiveExamPage_RoleStudentLiveExam /> },
      { path: "/student/profile", element: <StudentProfilePage_RoleStudentProfile /> },
      { path: "/student/results", element: <StudentResultsPage_RoleStudentResults /> },
      { path: "/student/timetable", element: <StudentTimetablePage_RoleStudentTimetable /> },
      { path: "/student/leave", element: <StudentLeavePage /> }
];
