#!/usr/bin/env node
/**
 * Auto-generate src/routes/generated-routes.tsx by walking
 * src/pages/role/<role>/... and producing one route entry per page directory.
 *
 *   node scripts/gen-routes.mjs
 */

import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT = path.resolve(__dirname, "..");
const PAGES_BASE = path.resolve(ROOT, "src/pages/role");
const OUT = path.resolve(ROOT, "src/routes/generated-routes.tsx");

const ROLES = ["admin", "teacher", "parent", "student"];

async function findPageFiles(dir) {
  const out = [];
  let entries;
  try {
    entries = await fs.readdir(dir, { withFileTypes: true });
  } catch {
    return out;
  }
  for (const entry of entries) {
    const p = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...(await findPageFiles(p)));
    else if (entry.name === "index.tsx") out.push(p);
  }
  return out;
}

function paramSegmentToRouterPath(segment) {
  if (segment.startsWith("Catchall_")) return "*";
  if (segment.startsWith("Param_")) return `:${segment.replace(/^Param_/, "")}`;
  return segment;
}

function routePathFor(role, segments) {
  const trimmed = segments.filter((s) => s !== "index.tsx");
  const cleaned = trimmed.map(paramSegmentToRouterPath).join("/");
  return cleaned ? `/${role}/${cleaned}` : `/${role}`;
}

function importNameFor(role, segments) {
  const parts = ["role", role, ...segments.filter((s) => s !== "index.tsx")];
  // Convert dashes/brackets to camel.
  const name = parts
    .map((p) =>
      p
        .replace(/^Param_/, "Param_")
        .replace(/^Catchall_/, "Catchall_")
        .replace(/[-_]/g, " ")
        .replace(/\b\w/g, (c) => c.toUpperCase())
        .replace(/\s+/g, "")
    )
    .join("");
  return `${name}Page`;
}

async function readNamedExportFromFile(filePath) {
  const text = await fs.readFile(filePath, "utf8");
  const match = text.match(/export\s+function\s+(\w+)\s*\(/);
  return match ? match[1] : null;
}

async function main() {
  const records = [];
  for (const role of ROLES) {
    const files = await findPageFiles(path.join(PAGES_BASE, role));
    for (const file of files) {
      const rel = path.relative(path.join(PAGES_BASE, role), file);
      const segments = rel.split(path.sep);
      const folderSegments = segments.slice(0, -1);

      const realExport = await readNamedExportFromFile(file);
      if (!realExport) {
        console.warn(`No named export found in ${file} — skipping`);
        continue;
      }

      const localPath = `@/pages/role/${role}/${
        folderSegments.length ? folderSegments.join("/") + "/" : ""
      }`.replace(/\/$/, "");
      const importPath = folderSegments.length
        ? `@/pages/role/${role}/${folderSegments.join("/")}`
        : `@/pages/role/${role}`;

      const routePath = routePathFor(role, folderSegments);
      const importLocal =
        realExport + "_" + importNameFor(role, folderSegments).replace(/Page$/, "");
      records.push({
        role,
        path: routePath,
        importPath,
        realExport,
        alias: importLocal,
      });

      void localPath;
    }
  }

  const importsByPath = new Map();
  for (const r of records) {
    if (!importsByPath.has(r.importPath)) importsByPath.set(r.importPath, []);
    importsByPath.get(r.importPath).push({ realExport: r.realExport, alias: r.alias });
  }

  const importLines = [];
  for (const [imp, items] of importsByPath.entries()) {
    const dedup = new Map();
    for (const it of items) {
      // each module has exactly one named export (re-running the generator
      // with multiple aliases would break tree-shaking but more importantly
      // create dup names). Use the alias as the local name.
      dedup.set(it.realExport, it.alias);
    }
    const parts = [...dedup.entries()].map(([orig, alias]) =>
      orig === alias ? orig : `${orig} as ${alias}`
    );
    importLines.push(`import { ${parts.join(", ")} } from "${imp}";`);
  }

  const groupedByRole = {};
  for (const r of records) {
    if (!groupedByRole[r.role]) groupedByRole[r.role] = [];
    groupedByRole[r.role].push(r);
  }

  const renderRoutesForRole = (role) =>
    (groupedByRole[role] || [])
      .map(
        (r) =>
          `      { path: ${JSON.stringify(r.path)}, element: <${r.alias} /> }`
      )
      .join(",\n");

  const out = `/* AUTO-GENERATED by scripts/gen-routes.mjs. Do not edit by hand. */
import type { RouteObject } from "react-router-dom";

${importLines.join("\n")}

export const adminRoutes: RouteObject[] = [
${renderRoutesForRole("admin")}
];

export const teacherRoutes: RouteObject[] = [
${renderRoutesForRole("teacher")}
];

export const parentRoutes: RouteObject[] = [
${renderRoutesForRole("parent")}
];

export const studentRoutes: RouteObject[] = [
${renderRoutesForRole("student")}
];
`;

  await fs.writeFile(OUT, out);
  console.log(`Wrote ${OUT} (${records.length} routes)`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
